# Generated by Django 4.1.13 on 2024-05-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Published_on', models.IntegerField()),
                ('Sales_in_millions', models.IntegerField()),
                ('Genre', models.CharField(max_length=50)),
            ],
        ),
    ]
